### ISSUE TITLE
Request: Rename toJSON → toBasicObject

### ISSUE THREAD

**Issue by anko** [GianlucaGuarini/icaro#1]
To me, [JSON](http://json.org/) means the text format that JavaScript's built-in [`JSON`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) library is designed to operate on, with `JSON.stringify` and `JSON.parse`.

However, calling `toJSON` on an icaro-wrapped object returns _an object_ (not _JSON_), which is confusing.

Could we rename it?  I'd suggest `obj.toBasicObject`.

**Comment by GianlucaGuarini** [comment]
In icaro I am using standards and `toJSON` [is the method](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) `JSON.stringify` uses to convert anything into a string. I don't see any reason to rename this method but thanks for asking anyway

**Comment by anko** [comment]
Oh man, JavaScript's own naming is confusing. :sweat: Seeing [that](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior), I agree. It would be bad to fight the language spec.
