### ISSUE TITLE
npm run test fails on windows

### ISSUE THREAD

**Issue by ghost** [GianlucaGuarini/icaro#12]
`npm run test` fails on windows due to relative path in script.

`npm run lint && ./node_modules/.bin/mocha test`

**Comment by ghost** [comment]
Can it be solved by installing `mocha` and `eslint` globally in `.travis.yml` ?

and then doing this in `test` script,

`npm run lint && mocha test`

**Comment by GianlucaGuarini** [comment]
fixed with https://github.com/GianlucaGuarini/icaro/pull/13 thank you
