### ISSUE TITLE
How does this compare to virtual DOM?

### ISSUE THREAD

**Issue by selforganized** [GianlucaGuarini/icaro#7]
Hi,

Virtual DOM is also used to improve performance of DOM updates. Is there any benchmark comparing icaro performance to something like React? Can icaro be used together with React?

**Comment by GianlucaGuarini** [comment]
Icaro is just the data layer in your application that will efficiently let you know when your data were updated and also what was updated. The React Virtual DOM is one of the 1000 different ways you can use to update your DOM node (see for example also [incremental-dom](https://github.com/google/incremental-dom),  [hyperHTML](https://github.com/WebReflection/hyperHTML)). In conclusion `icaro` will not tell you how to update your DOM so comparing it to the React Virtual DOM is like comparing bananas to apples.

> Is there any benchmark comparing icaro performance to something like React?

There are benchs linked in the readme file but comparing it to libs with similar purposes https://github.com/GianlucaGuarini/icaro#performance

> Can icaro be used together with React?

yes of course but at moment I am not interested into publishing any framework specific implementation. I am planning to use `icaro` as data layer for the next [riot](https://github.com/riot/riot) major release though

Let's keep in touch ;)
